---
- name: install httpd
  hosts: all
  tasks:
   - name: install apache httpd
     apt:
      name: apache2
      state: present

   - name: daemon reload
     systemd: 
      daemon_reload: yes

   - name: systemd starts httpd service
     systemd:
      state: started
      name: httpd

   
