---
- name: update web, nfs and db servers
  hosts: slave1 
  become: yes
  tasks:
    - name: ensure wireshark is at the latest version
      yum:
        name: wireshark
        state: latest

    - name: install unzip
      yum:
        name: unzip
        state: present
      when: inventory_hostname in groups ['slave1']
