---
- name: create direc
  hosts: slave1
  vars: 
   myscript: |
    "#! /usr/bin/sudo bash"
    useradd -m -s /bin/bash darey
    echo -e "cnl12345\ncnl12345" | sudo passwd "darey"
  tasks:
   - name: create dir and add file 
     file:
      path : /var/lib/jenkins/created_dir
      state: directory
      mode: '0775'

   - name: create a script in dir created above
     copy:
      dest: /home/ubuntu/script.sh
      content: 
       "#! /usr/bin/sudo bash"
       "useradd -m -s /bin/bash darey"
       echo -e "cnl12345\ncnl12345" | sudo passwd "darey"
      mode: '777'

    - name: copy the script to another location
      copy:
       src: /home/ubuntu/script.sh
       dest: /var/lib/jenkins/created_dir
       remote_src: yes

   - name: check if script above exists
     stat:
      path: /var/lib/jenkins/created_dir/script.sh
     register: check_exists

   - name: print if it exists
     debug: 
      var: check_exists
      
